### ISSUE TITLE
PDFs in the /pdf directory are all invalid 15 byte files

### ISSUE THREAD

**Issue by dfex** [JNPRAutomate/JNPRAutomateDemo-Class#1]

**Comment by RobWC** [comment]
I updated the PDFs. They aren't perfect yet but at least they aren't dead files!

https://github.com/JNPRAutomate/JNPRAutomateDemo-Class/releases/tag/v1.2

**Comment by RobWC** [comment]
Looks good and I also concatenated them all into a single file 

https://github.com/JNPRAutomate/JNPRAutomateDemo-Class/releases/tag/v1.3
